export const FETCH_PARKINGS_SUCCESS = 'FETCH_PARKINGS_SUCCESS';
export const FETCH_PARKINGS_PENDING = 'FETCH_PARKINGS_PENDING';
export const FETCH_PARKINGS_FAILED = 'FETCH_PARKINGS_FAILED';

export const BOOK_SLOT_SUCCESS = 'BOOK_SLOT_SUCCESS';
export const BOOK_SLOT_PENDING = 'BOOK_SLOT_PENDING';
export const BOOK_SLOT_FAILED = 'BOOK_SLOT_FAILED';

export const UNBOOK_SLOT_SUCCESS = 'UNBOOK_SLOT_SUCCESS';
export const UNBOOK_SLOT_PENDING = 'UNBOOK_SLOT_PENDING';
export const UNBOOK_SLOT_FAILED = 'UNBOOK_SLOT_FAILED';

export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export const FETCH_BOOKINGS_PENDING = 'FETCH_BOOKINGS_PENDING';
export const FETCH_BOOKINGS_FAILED = 'FETCH_BOOKINGS_FAILED';
